package io;

import java.util.List;

public interface OutputHandler {

    /**
     * @return the last message sent
     */
    Message getLastMessage();

    /**
     * @param text to be displayed on screen
     * Display text on screen
     */
    void generateText(String text);

    /**
     * @param text to be displayed on screen
     * @param options to be displayed on screen
     * If options is null, same behaviour as generateText(text)
     * Display text and options on screen
     */
    void generateTextWithOptions(String text, List<String> options);

    /**
     * @param message the message to display
     * Used in case a message object is generated by getLastMessage.
     * Other overloaded methods are present for more flexibility.
     * Displays the message on screen.
     */
    void generateText(Message message);
}

